### ISSUE TITLE
Anchor has inconistant icon annimation

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#123]
In the anchor examples, on [icon + label], the icon grows on hover, but for icon, it only changes to #fff, no grow.

https://grommet.github.io/hpe/docs/anchor/examples#3
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

**Comment by ericsoderberghp** [comment]
That's by design. We can discuss.

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit c70f84981aab9dd70739344c8d19b64b1eda7806.
