### ISSUE TITLE
Anchor Button example should be consistent with Anchor example

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#125]
At a minimum, [Icon,Label,Plain] button example should be the same as [Icon, Label] Anchor example.

Button: https://grommet.github.io/hpe/docs/button/examples#6
Anchor: https://grommet.github.io/hpe/docs/anchor/examples#2

[Icon,Label,Plain] button example currently only changes the icon color. Currently there is no grow of icon and no underline of label. 
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

**Comment by ericsoderberghp** [comment]
This is by design. We can discuss.

**Comment by bryanjacquot** [comment]
Fixed.
