### ISSUE TITLE
All Dark Theme card examples font unreadable

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#126]
Dark theme on all card examples, have #fff font color with light grey backgrounds. We should have either a tile background color change to match the dark theme, or keep the font color #333 on dark theme when tile background color is light.
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 2 56 06 pm](https://cloud.githubusercontent.com/assets/13038855/19055614/b9adc542-8979-11e6-9d5e-ce7f2f25594f.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit d553b3337616f7ac14b0f41bec624e6a3eb50dcb.
