### ISSUE TITLE
Icon Distribution example can't match dark theme for transparency

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#127]
We need a different way to show value on icon distribution example. The transparent background on the value can't dynamically read the dark theme to match it.
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 3 11 26 pm](https://cloud.githubusercontent.com/assets/13038855/19056185/8c687f48-897c-11e6-84b1-66c8f32f4f39.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 4abbf7ec0c6d7239fa3bed82b91b04f55a7ddb56.
