### ISSUE TITLE
Dropdown values are larger than dropdown label

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#128]
On click on a dropdown, the values inside the dropdown are larger than the dropdown label. 
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 3 26 04 pm](https://cloud.githubusercontent.com/assets/13038855/19056388/c929c350-897d-11e6-81bb-a92a788506f3.png)

**Comment by ericsoderberghp** [comment]
Fixed recently.
