### ISSUE TITLE
Header examples navigation not collapsing menu options

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#130]
For all header examples, starting at example 0, when I use the right arrow to navigate through the Header examples, the menu options are not collapsing into their dropdown label. 

Example: on header example 1 (screenshot below) the First, Second, Third labels are suppose to be collapsed under a dropdown. When I navigate to example 4 and then back to example 1, the menu items are collapsed properly. 

https://grommet.github.io/hpe/docs/header/examples#0
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 4 04 56 pm](https://cloud.githubusercontent.com/assets/13038855/19057225/28d23cce-8983-11e6-86ba-cdbcd4907140.png)

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/4ddeb1ac9952c1c0b359ee2983f4a59eebc31857

**Comment by epilande** [comment]
Just found another issue with the Menu:

Should be collapsed as `Label`.
https://grommet.github.io/docs/header/examples#3
![image](https://cloud.githubusercontent.com/assets/3210082/19329106/c03b7daa-9072-11e6-99d7-7382775ad8dc.png)

Should have default icon (`...`)
https://grommet.github.io/docs/menu/examples#4
![image](https://cloud.githubusercontent.com/assets/3210082/19329100/bb315744-9072-11e6-980a-5115a46ae743.png)
