### ISSUE TITLE
Video Hero Example is missing video

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#131]
Besides the header alignment being not centered, the Video hero example is missing the video. 
https://grommet.github.io/hpe/docs/hero/examples#1
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 4 09 31 pm](https://cloud.githubusercontent.com/assets/13038855/19057320/cf091b76-8983-11e6-97de-b65443fa8b1a.png)

**Comment by bryanjacquot** [comment]
Fixed in https://github.com/grommet/grommet-docs/commit/e89c0354c41a90e978feac50feb36b6e4c96ee07
