### ISSUE TITLE
Form Select-Search and Select-No Search Icons are different colors

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#132]
In Form example 2, The first Select (Select-No Search) icon is lighter grey than the second Select (Select-Search) icon. First Select (Select-No Search) also needs an on hover color change.

https://grommet.github.io/hpe/docs/form/examples#2
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 4 19 02 pm](https://cloud.githubusercontent.com/assets/13038855/19057535/61fb78ce-8985-11e6-821e-59052928b78c.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 223fd9e2e0937bec4d4ee160e96c93ef52e79bba.
