### ISSUE TITLE
Layer Article example, footer doesn't stretch 100%

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#133]
Layer Article example has a footer that doesn't stretch to be 100% of the screen. 
https://grommet.github.io/hpe/docs/layer/examples#3
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 4 26 41 pm](https://cloud.githubusercontent.com/assets/13038855/19057664/67106d00-8986-11e6-978e-f10e8dbf3cc7.png)

**Comment by alansouzati** [comment]
Fixed by adding flush option to the article example

https://github.com/grommet/grommet-docs/commit/30be35300720c5e1279118c38dc1677ea864a298
