### ISSUE TITLE
Dark theme error message is inconsistent between Form and LoginForm examples

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#135]
Dark theme error message on Form examples are white when error message on LoginForm examples are red.

Form: https://grommet.github.io/hpe/docs/form/examples#2
LoginForm: https://grommet.github.io/hpe/docs/login-form/examples#1
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 4 37 33 pm](https://cloud.githubusercontent.com/assets/13038855/19057859/e3cc3d78-8987-11e6-9428-bdd862a1c4cb.png)

![screen shot 2016-10-03 at 4 40 32 pm](https://cloud.githubusercontent.com/assets/13038855/19057889/2008f4f2-8988-11e6-8a36-017a07aa2210.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 586f951cb64a9faf5d5dad901076bb21b96ce2d1.
