### ISSUE TITLE
Verticle map example isn't correctly responding

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#136]
On Map Example 0, selecting vertical, then resizing browser, the map doesnt quite wrap properly. There's some overlap on the third category. 

https://grommet.github.io/hpe/docs/map/examples#0
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 9 51 51 am](https://cloud.githubusercontent.com/assets/13038855/19083757/512c77b2-8a18-11e6-8c8b-710db3bd7429.png)

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/6dd9488f91a02579797ce62fc0fb3cb7356427b7
