### ISSUE TITLE
Menu Examples Dark Theme has on select background color

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#137]
All dark themed menu examples have a black background color on selected item. 

https://grommet.github.io/hpe/docs/menu/examples
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 10 06 17 am](https://cloud.githubusercontent.com/assets/13038855/19084173/48b3afa4-8a1a-11e6-85c3-db2e0b18cf55.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 4d8485391b283fc5a66a8ed2abeab6276c7db60e.
