### ISSUE TITLE
Menu dropdown labels dont have on hover color change

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#138]
The below screenshot is on hover of the dropdown menu example 6. The two icons change from grey to black but the label doesn't. 

Dark theme works fine.

https://grommet.github.io/hpe/docs/menu/examples#6
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 10 09 39 am](https://cloud.githubusercontent.com/assets/13038855/19084301/dd885c4c-8a1a-11e6-86d6-e25e10fa13ea.png)

**Comment by bryanjacquot** [comment]
This has been resolved.
