### ISSUE TITLE
Meter examples are missing "size" label in its meter size dropdown selection

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#139]
The dropdown for selecting a size of the meter example is missing its label. 

https://grommet.github.io/hpe/docs/meter/examples
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 10 18 53 am](https://cloud.githubusercontent.com/assets/13038855/19084614/241d4aae-8a1c-11e6-9a02-2a45c5033241.png)

**Comment by ericsoderberghp** [comment]
This is behaving as expected, since it allows having no size value set.

**Comment by bryanjacquot** [comment]
@ericsoderberghp I thought this was a bug too.  Should we make the default value something like `[default]` or `[unset]`
