### ISSUE TITLE
Animated load speed on Meters is inconsistant between arcs and bars

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#140]
The animated load speed on meters is very quick while bars follow a more slower, smoother load. 

The slower load was Grommet's original/earlier experience. 

Arc: https://grommet.github.io/hpe/docs/meter/examples#2
Bar: https://grommet.github.io/hpe/docs/meter/examples#6
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

**Comment by ericsoderberghp** [comment]
Agreed. But, this is tricky to fix. We have implemented the animations in a simple way using CSS dashes. Post 1.0, if ever.

**Comment by tracybarmore** [comment]
Backlog Grooming Jan 4, 2017 - Closing issue
