### ISSUE TITLE
Unknown Icon in Notification example has different status icon than other statuses

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#141]
We are using the status icnos that have the secondary icon inside the outer shape for status of OK, Warning, and Critical. But then Unknown we change to only the outer shape? 

Screenshot below also shows the sticker sheet examples. 

Notification OK: https://grommet.github.io/hpe/docs/notification/examples#3
Notification Unknown: https://grommet.github.io/hpe/docs/notification/examples#4
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 10 30 49 am](https://cloud.githubusercontent.com/assets/13038855/19085096/e4db249a-8a1d-11e6-8484-49220c3def35.png)

Sticker Sheet: 
![screen shot 2016-10-04 at 10 34 23 am](https://cloud.githubusercontent.com/assets/13038855/19085148/25cbc252-8a1e-11e6-94bc-bd1fa956a6fc.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit cda156e81ebfea60630f46e1c3bfb3a394a58825.
