### ISSUE TITLE
Percent Complete Notification Example needs spacing between meter and value

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#142]
Notification example 4, has a meter that has some spacing issues between the meter and its value. Screenshot below.

https://grommet.github.io/hpe/docs/notification/examples#4
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 10 54 00 am](https://cloud.githubusercontent.com/assets/13038855/19085962/1e5bfd54-8a21-11e6-9f11-8e552fdf1dcd.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 7bd4dcbf21f4a2c960dda4b5136035db3e6b4f3f.
