### ISSUE TITLE
Dark Theme font color on Notication Examples changes to white

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#143]
Since Unknown notifications stay with a grey background color, font color should also stay #333, even on dark themed and not change to white.

Notifications that need #333 font on dark theme:
https://grommet.github.io/hpe/docs/notification/examples#0
https://grommet.github.io/hpe/docs/notification/examples#1
https://grommet.github.io/hpe/docs/notification/examples#4
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 10 56 45 am](https://cloud.githubusercontent.com/assets/13038855/19086007/570f63e8-8a21-11e6-9024-139de2c5b90d.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit d553b3337616f7ac14b0f41bec624e6a3eb50dcb.
