### ISSUE TITLE
NumberInput allows decimal

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#144]
When entering a custom value in NumberInput, I can type in a decimal and then the decimal gets automatically removed when I enter in my next number. If we don't allow the decimal, should we even let the user type it in the first place?

https://grommet.github.io/hpe/docs/number-input
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 11 01 15 am](https://cloud.githubusercontent.com/assets/13038855/19086180/f654f148-8a21-11e6-9c40-166ea6015b84.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 74bba82a5a1d89338e89abe9ffcc9371d816e092 and grommet-docs commit e6acf311f83c3fe5995d6d33fd2a7306bc9f2a42.

**Comment by MarcoMedrano** [comment]
I think we actually should support decimals. Or how can I put decimals?

**Comment by alansouzati** [comment]
It supports decimal. Eric's fix was to remove the parseInt function that was there before.

**Comment by MarcoMedrano** [comment]
Hoo right it actually does, but does not allow it by typing (only by pressing the buttons + and -). 
Neither is possible to use the up and down arrows to change the value :( .

**Comment by MarcoMedrano** [comment]
Should I submit a bug? Think in the case I expect a value between 0 and 100 pounds. and I can have decimals, so I enable `step=0.1`. If the default value is `0` that means that I have to tap 1000 times to get to 100 pounds ..

**Comment by alansouzati** [comment]
I'm not sure I understand what you are asking. Can you create a codepen or something?

Check this codepen:

http://codepen.io/alansouzati/pen/KaqyQe?editors=0010

Step can be configured to be any interval you want, the configuration is in total control of the caller.

**Comment by MarcoMedrano** [comment]
Dam it, haha yours is working fine, hum I am using it with  `value={1}` , and that do not let me edit it by typing (using the keyword) but yes by pressing + and - buttons. 
[http://codepen.io/MarcoMedrano/pen/KaqyBB?editors=0010](http://codepen.io/MarcoMedrano/pen/KaqyBB?editors=0010)
Well it is a very weird behavior is in it?

However I see that I should use 'defaultValue={1}' which let me edit using the buttons and by typing.

**Comment by alansouzati** [comment]
yeah. this is straight from react controlled and uncontrolled components. check this out:

https://facebook.github.io/react/docs/forms.html
