### ISSUE TITLE
Licensing footer has gap in line wrapping in mobile

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#146]
The license footer on all pages has a huge gap in between its first and second line wraps with resizing the browser to a mobile size. 
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 11 11 18 am](https://cloud.githubusercontent.com/assets/13038855/19086545/704f4efc-8a23-11e6-9ea2-be44249a7c50.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit ea9034f9a34702fe473ecfb9ae67bb1cc0efccb9.
