### ISSUE TITLE
Lighter textfield border needed for Dark Themed Search Examples

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#147]
All search examples that have a border, currently have a border of black. We need the lighter textfield border like what's used in Form examples

https://grommet.github.io/hpe/docs/search/examples#8
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 11 21 48 am](https://cloud.githubusercontent.com/assets/13038855/19086893/e63a265e-8a24-11e6-89d0-35e663df8f4f.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 29be4a0d9a91c70dae0e5a03e731e28dc69a45ab.
