### ISSUE TITLE
"Paragraphs" link incorrect in Section component

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#148]
The "Paragraphs" link in the section component top paragraph is incorrect. 

The link is currently: https://grommet.github.io/hpe/docs/pargraph
It should be: https://grommet.github.io/hpe/docs/paragraph

Should also add appropriate spacing between links in this paragraph. 
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 11 25 17 am](https://cloud.githubusercontent.com/assets/13038855/19087030/721ebbb2-8a25-11e6-831a-ec91fa5795a4.png)

**Comment by bryanjacquot** [comment]
Fixed in https://github.com/grommet/grommet-docs/commit/e89c0354c41a90e978feac50feb36b6e4c96ee07
