### ISSUE TITLE
Select component in Firefox won't allow modification to search input

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#149]
To Duplicate in Firefox: 
- Go to https://grommet.github.io/hpe/docs/select/
- "One" by default is already selected
- Click dropdown icon
- Search "fi" to return five as suggestions
- Click outside component
- Reopen dropdown (cursor is now before the "fi" entered earlier.
- Click inside searchinput to move cursor to after "fi"
- It doesn't allow it. It closes the select.

I can only modify my previous search input if I use my arrow key to move the cursor manually to the right. 
### Your Environment
- Browser Name and version: Firefox 48.0

![screen shot 2016-10-04 at 11 29 43 am](https://cloud.githubusercontent.com/assets/13038855/19087187/ffe39d96-8a25-11e6-95c4-fd3c80c95fa7.png)

**Comment by alansouzati** [comment]
Fixed
