### ISSUE TITLE
Dark Theme Table examples need lighter column header bottom border

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#151]
Tables with header examples all need to be changed from black border to light grey border to show up on dark theme.

https://grommet.github.io/hpe/docs/table/examples#1
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 2 38 44 pm](https://cloud.githubusercontent.com/assets/13038855/19093570/7ac74b92-8a40-11e6-9b38-ae1343c9fbfe.png)

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 586f951cb64a9faf5d5dad901076bb21b96ce2d1.
