### ISSUE TITLE
Dark Theme Selectable Table examples need lighter selection

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#152]
Tables that have selectable rows, need their selection color to be lighter to be visible on dark theme. 

https://grommet.github.io/hpe/docs/table/examples#1
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 2 43 56 pm](https://cloud.githubusercontent.com/assets/13038855/19093701/ffda48fc-8a40-11e6-9725-fd057db07f11.png)

**Comment by ericsoderberghp** [comment]
Also an issue on Tiles and List.
Also need to tone down the hover indicator.

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 629e02becb32246a9ecdd898a5c7db087fd35a9a.
