### ISSUE TITLE
Tiles in Tiles Examples should follow its parent page named "Title(s)"

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#154]
To keep consistency between parent and child (examples) pages, our component titles should be named the same as well. We should change "Tiles Examples" to "Title(s) Examples".

https://grommet.github.io/hpe/docs/tiles/examples
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

**Comment by bryanjacquot** [comment]
Will change page title to be "Tiles"

**Comment by bryanjacquot** [comment]
Fixed in https://github.com/grommet/grommet-docs/commit/e89c0354c41a90e978feac50feb36b6e4c96ee07
