### ISSUE TITLE
Row Tile Example is not loading right faded tile under arrow nav

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#155]
On tile example 4, the far right tile is suppose to be faded to allow for the arrow on top to be visible. But on load of this example, the tile does not fade until I interact with the component.

https://grommet.github.io/hpe/docs/tiles/examples#4
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-04 at 2 59 16 pm](https://cloud.githubusercontent.com/assets/13038855/19094085/2ec61054-8a43-11e6-92ce-dcda1fb92d40.png)

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/717cf5db593a6c5d548e0ab3ada377d49b5da494
