### ISSUE TITLE
Dark Theme, Tile, font color shouln't change to black if it doesnt have a tile background color

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#157]
Simple tile (example 0) stays black font when it doesn't have a tile background color. 

https://grommet.github.io/hpe/docs/tiles/examples/#0
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

<img width="509" alt="screen shot 2016-10-05 at 7 52 07 am" src="https://cloud.githubusercontent.com/assets/13038855/19118266/c3e93f0c-8ad0-11e6-88bf-0d0bff65f8d2.png">

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit d553b3337616f7ac14b0f41bec624e6a3eb50dcb.
