### ISSUE TITLE
Dark Theme, Tile, Examples dont change to dark theme

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#158]
Tile examples don't change when toggling between light and dark theme.

Examples that don't change properly:
https://grommet.github.io/hpe/docs/tiles/examples/#2
https://grommet.github.io/hpe/docs/tiles/examples/#4
https://grommet.github.io/hpe/docs/tiles/examples/#5
https://grommet.github.io/hpe/docs/tiles/examples/#6
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

<img width="603" alt="screen shot 2016-10-05 at 7 54 51 am" src="https://cloud.githubusercontent.com/assets/13038855/19118421/2d2d2168-8ad1-11e6-8db6-72a936f91d84.png">

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit d553b3337616f7ac14b0f41bec624e6a3eb50dcb.
