### ISSUE TITLE
Topology connector is cutting off in example

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#159]
The curved connector int he topology example is being cut off at the edges of the connected containers. 

https://grommet.github.io/hpe/docs/topology
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

<img width="296" alt="screen shot 2016-10-05 at 8 04 07 am" src="https://cloud.githubusercontent.com/assets/13038855/19118782/5d9a491a-8ad2-11e6-950f-3fad61688530.png">

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit 427b510b836535324ac3aab537aebef1d2905074.
