### ISSUE TITLE
Dark Theme, Value, Examples dont change to dark theme

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#160]
ALL Value examples aren't changing when toggling between light and dark theme.
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

<img width="419" alt="screen shot 2016-10-05 at 8 08 03 am" src="https://cloud.githubusercontent.com/assets/13038855/19118915/de55ff36-8ad2-11e6-83f8-324582ef4989.png">

**Comment by ericsoderberghp** [comment]
Fixed in grommet commit d553b3337616f7ac14b0f41bec624e6a3eb50dcb.
