### ISSUE TITLE
About Page is still TBD

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#162]
We need to fill in the About page or remove it.
https://grommet.github.io/hpe/docs/about

**Comment by L0ZZI** [comment]
About page design is done. Waiting for dev...

**Comment by RyanCCollins** [comment]
@L0ZZI where can I find the designs for this?  I'd have fun putting this together.

**Comment by tracybarmore** [comment]
@RyanCCollins - I DMed you the file. Have fun!

**Comment by RyanCCollins** [comment]
Awesome, thank you @tracybarmore.  I've moved this to in progress.

**Comment by RyanCCollins** [comment]
Completed with #233
