### ISSUE TITLE
Docs embedded links to navigate between pages doesn't load at page top

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#164]
When there is an embedded link in a docs page, I click the link, it navigates me to another docs page, but scroll doesn't start from the top of the page.

Duplication steps:
- Go to https://grommet.github.io/hpe/docs/hello-world
- Scroll to page bottom
- Under Next Steps section, click on "Get Started" link
- Get Started page loads anchored to scroll position I was at on Hello World page

I would expect on click of Get Started link that the Get Started page would load with scroll position at the top of the page.
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

**Comment by ericsoderberghp** [comment]
Fixed in 09ecfadaefd40d8c240de49cab9d622804f451e2.
