### ISSUE TITLE
Patterns Example Pages

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-docs#165]
Create example pages for the following patterns: 
- [ ] Primary Page
- [ ] Sub Page
- [ ] Detail Page
- [ ] Feed Page
- [ ] Vertical Narrative
- [ ] Horizontal Narrative
- [ ] Single Page Narrative
- [ ] Split Pane
- [ ] Forms

**Comment by L0ZZI** [comment]
Hey man, do we need this anymore? Can we add it to #984? As an implementation detail.

**Comment by karatechops** [comment]
@L0ZZI that's fine. I initially created a few issues to keep track of the Patterns implementation as they were relatively large tasks. I'm fine with lumping everything in one place -- I just figured it would be easier to move around cards on large tasks.
