### ISSUE TITLE
Chart import statement in docs is incomplete

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet-docs#171]
### Expected Behavior

Docs should have correct import statement
`import Chart, { Axis, Base, Layers, Line } from 'grommet/components/chart/Chart';`
### Actual Behavior

Docs show the following import statement (notice the missing _Chart_ element of the path.
`import Chart, { Axis, Base, Layers, Line } from 'grommet/components/chart';`
### URL or screen shot exhibiting the issue

![image](https://cloud.githubusercontent.com/assets/6393696/19397121/b3d8c5da-9203-11e6-8382-0c1e6121934b.png)
### Steps to Reproduce
1. Try to use path from docs, and it doesn't work.

**Comment by ericsoderberghp** [comment]
Fixed in 0c3ae23bf5ae88486ab92898371be90b412734bd.
