### ISSUE TITLE
Why Grommet section of home page has issues with IE11

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet-docs#176]
### Expected Behavior

Why Grommet section should render properly on supported browsers.
### Actual Behavior

Tiles are overlapping on Windows 7 with IE 11
### URL or screen shot exhibiting the issue

![image](https://cloud.githubusercontent.com/assets/6393696/19540307/b635fd7c-961b-11e6-8ea9-31f68413beb4.png)
### Steps to Reproduce
1.  Visit homepage with IE 11.
### Your Environment
- Browser Name and version: IE 11

![image](https://cloud.githubusercontent.com/assets/6393696/19540328/dcac52ee-961b-11e6-9eb3-1a3d216c6de1.png)
- Operating System and version (desktop or mobile): Windows 7 desktop

Also reproduced with BrowserStack Windows 7 and IE 11.

**Comment by tracybarmore** [comment]
Fixed by @alansouzati
