### ISSUE TITLE
Selecting Aruba theme from Grommet.io homepage breaks selector.

### ISSUE THREAD

**Issue by L0ZZI** [grommet/grommet-docs#18]
http://www.grommet.io/docs/aruba/
![screenshot 2016-01-22 12 55 48](https://cloud.githubusercontent.com/assets/1753301/12522802/8f57b090-c107-11e5-8a1e-1433792cd854.png)

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet-docs/commit/83bbea344800a205b608018e448671fc01fccd6a
