### ISSUE TITLE
Skip down link remains at the bottom of the page on Grommet.io homepage.

### ISSUE THREAD

**Issue by L0ZZI** [grommet/grommet-docs#19]
![screenshot 2016-01-22 12 56 01](https://cloud.githubusercontent.com/assets/1753301/12522983/d817d886-c108-11e5-95a1-2f7f8354ae3a.png)

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/bd91a3f728b90aa0c636e1ee39568c456630d966
