### ISSUE TITLE
Guides on the docs are weirdly formatted in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet-docs#2]
Not only do they get the fun style flash, but they go from vertical layout to horizontal in IE11 with overlapping.

Examples

![image](https://cloud.githubusercontent.com/assets/13527666/11076039/cd8040a2-87b5-11e5-9be4-2599324bd077.png)

![image](https://cloud.githubusercontent.com/assets/13527666/11076046/d51a25ee-87b5-11e5-94cc-3a6002892a58.png)

![image](https://cloud.githubusercontent.com/assets/13527666/11076049/dc134cb8-87b5-11e5-94b2-7c67ba9f2fdd.png)

![image](https://cloud.githubusercontent.com/assets/13527666/11076025/b43ec6cc-87b5-11e5-9d26-b12c534d460a.png)

**Comment by ericsoderberghp** [comment]
Cannot reproduce on IE11.
