### ISSUE TITLE
Label has a margin attr but it's undocumented.

### ISSUE THREAD

**Issue by woodm1979** [grommet/grommet-docs#225]
The help page for Label does not list "margin"

### Expected Behavior

The help page for Label should list margin as a property

### Actual Behavior

The help page for Label does not list margin as a property

### URL or screen shot exhibiting the issue
https://grommet.github.io/docs/label

### Steps to Reproduce
 1. Go to https://grommet.github.io/docs/label
 2. read the lack of "margin" properties
 3. 

### Your Environment
* Browser Name and version:
Chrome, but it's not relevant
* Operating System and version (desktop or mobile):
Mac OS-X, but it's not relevant

**Comment by RyanCCollins** [comment]
There is a pending PR for this #226 that has been closed out and needs to be merged
