### ISSUE TITLE
Text runs together and is truncated on Grommet home page in IE 11

### ISSUE THREAD

**Issue by cherih** [grommet/grommet-docs#232]
### Expected Behavior
In the "What makes us great" section, complete paragraphs of text should be shown for each item (Comprehensive, Active, Flexible and Accessible) and there should be separation between each paragraph.

This works correctly in the Chrome browser.

### Actual Behavior
The paragraphs for the items in the "What makes us great" section run together and don't contain all of the verbiage in the paragraphs. 

### URL or screen shot exhibiting the issue
![home-page-paragraphs-run-together](https://cloud.githubusercontent.com/assets/25066338/22166745/d25affdc-df1f-11e6-8a97-db42410f8880.PNG)

### Steps to Reproduce
 1.  Browse to the grommet home page - https://grommet.github.io/
 2.  Scroll down to the "What makes us great" section and view the items in this section.

### Your Environment
* Browser Name and version: Internet Explorer 11.0.38
* Operating System and version (desktop or mobile): Windows 7 Enterprise with SP1

**Comment by tracybarmore** [comment]
Thanks for bringing this to our attention. We have validated this and are looking in to it. Thanks!

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/92db0e0a62a044ac77db0578dc4b4d407357aa22
