### ISSUE TITLE
Update Get Started page

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#248]
https://grommet.github.io/docs/get-started
@L0ZZI TBA on finished design

**Comment by tracybarmore** [comment]
Carlozzi updated sketch file
- Path: https://github.com/grommet/hpe-design/tree/master/mockups/grommet-website
- File: grommet-nav-rework.sketch
- Artboard: 04 - Install, Desktop

**Comment by dgennetten** [comment]
I'm confused. Artboard 04 - Install, Desktop shows yet another variation on the Start left nav. Which is correct?

**Comment by tracybarmore** [comment]
Deprecating card until hashed out design is in place.
