### ISSUE TITLE
Need Component Search

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet-docs#249]
I appreciate the benefit of the categorized list in Components, but it is frustration when I know exactly which component I want to look up and I have to spend a couple seconds looking for it in the left nav.

**Comment by tracybarmore** [comment]
Linking with grommet/grommet-design#49

**Comment by dgennetten** [comment]
This still bugs the heck out of me. Quick, without looking, tell me what section ```Value``` is in. Bet you can't.

**Comment by RyanCCollins** [comment]
I think a search would solve this issue.  I agree, as a frequent user of the docs, this is an area that bugs me.

It is also very frustrating to find the right icon in the docs.  Sometimes I spend 10 minutes trying to remember what it's named.  Having another way to search through them would be really helpful.  Perhaps a tagging system or a way to add multiple names to each icon?

**Comment by dgennetten** [comment]
This still frustrates. I'm in there frequently and still find I'm scanning up and down the list half the time, rather than first divining which category to look in. Search would be great (as it now is for grommet-icons).

**Comment by alansouzati** [comment]
fully agree that it should be easy to scan for grommet components. I often find myself using the browser native search component and it works fine, you can trigger that using `command + f`.

**Comment by L0ZZI** [comment]
This will be a much shorter list in the grommet v2 site. ;-)
