### ISSUE TITLE
Responsive docs page  "componentWillUnmout {"

### ISSUE THREAD

**Issue by woodm1979** [grommet/grommet-docs#259]
https://grommet.github.io/hpe/docs/responsive

spelling error on componentWillUnmout and also is missing "()"

### Expected Behavior
Unmount has 2 n's and the docs should include the "()" to make it a function.

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by dgennetten** [comment]
Fixed https://github.com/grommet/grommet-docs/commit/dd96412f87f68c993b8e2fbb4dfcd972e4c2f306
