### ISSUE TITLE
onMore property

### ISSUE THREAD

**Issue by AlessiaPileri** [grommet/grommet-docs#271]
Hi all,
I'm using onMore property on List component to create an infinite scrolling on my page. Can I hide the spinner at the bottom of the list when I reach the end of data?
Thanks

**Comment by alansouzati** [comment]
Very good question.

Yes you can. Here is how I would do it:

```
let onMore = () => ...;
if (currentList.length === totalList.length) {
  onMore = undefined;
}
<List onMore={onMore}>...
```

Hope it helps 👍 

I'm closing this issue since I believe there is nothing to be done on the Grommet side of things. Feel free to reopen if you think otherwise
