### ISSUE TITLE
Improve documentation for Tab

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet-docs#272]
Tabs doc does not describe the properties for the Tab component.

**Comment by cherih** [comment]
Added a Tab Properties section to the Tabs doc page. The only property described in this new section is the title property. All other Tab properties are used by the Tabs component and should not be specified by the user.

This is patterned after the List doc page, which shows both List and ListItem properties.

**Comment by cherih** [comment]
This issue was fixed by PR #280.
