### ISSUE TITLE
Grommet.io Anchor page bug

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-docs#281]
The grommet.io [anchor page](https://grommet.github.io/docs/anchor/) is currently displaying a render blocking error. `Cannot read property 'map' of undefined`. I pulled the latest master branch and don't see the issue locally and I'm not able to infer much from the `heroku` branch as when I run this locally it forwards me to the grommet.io url.

![screen shot 2017-07-29 at 12 24 16 pm](https://user-images.githubusercontent.com/5983843/28746419-03696490-745a-11e7-8f16-302d6d29d9a3.png)

The anchor doc code hasn't been changed for quite some time so I'm assuming this is a react-desc bug.

**Comment by alansouzati** [comment]
I will check this later today. Thanks for reporting it

**Comment by alansouzati** [comment]
I've fixed it. it was indeed a problem with react-desc
