### ISSUE TITLE
Docs need to tone down Sketch connection. Scaring people away...

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet-docs#293]
### Expected Behavior

See closed grommet issue #1630.  This is one of multiple instances of new prospects getting the wrong idea that they NEED sketch to use grommet.

**Comment by L0ZZI** [comment]
Hmm...We'll at the time it was true. If you want to design mock elements for use in Grommet then Sketch is a big part but development-wise it has no consequence. We're going to attack design assets in 2.0 differently to accommodate more platforms.
