### ISSUE TITLE
Charts Ticker update causes Out of stack space error on IE11 and freezes UI

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet-docs#3]
Whenever the Ticker series data is updated in IE there's a 'SCRIPT28: Out of stack space' error in IE11.

This is true whether using original draw, setState, or forceUpdate with the series data.

While it is getting to the Out of stack space error it freezes the entire UI. It does update after the error, which is somewhat disconcerting.

**Comment by epilande** [comment]
Hi @kylebyerly-hp I'm not too sure which component you're referring to, I don't see any Ticker component within Charts. Could we get more information and or screenshots of the issue.

**Comment by bryanjacquot** [comment]
We will evaluate a ticker with new charts to be sure there's no memory leaks.

**Comment by bryanjacquot** [comment]
The new chart component does not suffer from this stack space error.   I opened the updating chart in IE and left it running for 20 minutes.  

http://grommet.github.io/docs/chart-examples/#5  

The JavaScript console was clean and the memory usage remained stable (actually decreased a bit) over that period.
