### ISSUE TITLE
Some of the sticker sheet links on the Resources page are broken

### ISSUE THREAD

**Issue by cherih** [grommet/grommet-docs#309]
The following sticker sheet links are broken:
- HPE Icons (sketch and pdf)
- Aruba
- Micro Focus
- DXC

### Expected Behavior
Click on sticker sheet link and have it download the sticker sheet file. (Click on the HPE components sticker sheet for an example of how this should work.)

### Actual Behavior
Clicking on a broken link causes a new page to be displayed with a 404 error - This is not the web page your are looking for.

### Steps to Reproduce
 1.  Browse to http://grommet.io/docs/resources
 2. Click on the broken links 

### Your Environment
* Browser Name and version: Chrome and IE11
* Operating System and version (desktop or mobile): Windows

**Comment by cherih** [comment]
There also appear to be missing links for additional sketch and pdf files:
- Grommet components and templates
- Aruba components and templates
- Micro Focus components and templates
- DXC components and templates

Some of the links are not up to date:
- HPE components pdf and templates (sketch and pdf)

**Comment by L0ZZI** [comment]
Links work appropriately. @dgennetten can you validate?

**Comment by ShimiSun** [comment]
Feel free to reopen if still relevant
