### ISSUE TITLE
Double vertical scrollbars in the main content section (see screenshot)

### ISSUE THREAD

**Issue by phuson** [grommet/grommet-docs#31]
![screen shot 2016-02-25 at 5 15 46 pm](https://cloud.githubusercontent.com/assets/7669/13340229/8d43119a-dbe3-11e5-8c9d-f0fdfb930b29.png)

This is happening on Safari, Chrome, and Firefox browsers running on OSX Yosemite 10.10.5.

Removing `overflow-y: scroll` on `html` seems to fix the issue (see screenshot below). I haven't seen this before so it seems like this might be introduced by the latest changes in Grommet?

![screen shot 2016-02-25 at 5 20 44 pm](https://cloud.githubusercontent.com/assets/7669/13340321/41d35c96-dbe4-11e5-8f46-4e682fabbb7d.png)

**Comment by phuson** [comment]
Hmm, it seems like the overflow-y comes from inuitcss/base.page: https://github.com/inuitcss/base.page/blob/master/_base.page.scss#L24

Is it possible that there was a rule that overrode this that may have gotten removed recently?

**Comment by ericsoderberghp** [comment]
Fixed in grommet 00552e32a10b0c44ae3fc343c0e03ec8563f2dee.
