### ISSUE TITLE
http:// should be updated to https://

### ISSUE THREAD

**Issue by georgediaz** [grommet/grommet-docs#315]
### Expected Behavior
http:// should be updated to https:// for security and so chrome doesn't flag the site as unsecure.

### Actual Behavior
http://grommet.io is being flagged as unsecure.

### URL or screen shot exhibiting the issue
http://grommet.io

### Steps to Reproduce
 1. Go to http://grommet.io

### Your Environment
* Browser Name and version: Chrome, any version
* Operating System and version (desktop or mobile): Mac desktop/mobile

**Comment by ShimiSun** [comment]
Fixed, thanks @georgediaz !
