### ISSUE TITLE
Please link your own resources

### ISSUE THREAD

**Issue by ssured** [grommet/grommet-docs#319]
In github issues I found a link to https://codesandbox.io/u/grommetux/sandboxes somewhere. This is an awesome resource for people like me starting with Grommet. I think this weekly snippet should be linked from the main docs page.

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
@ssured thanks for your input. the link you mentioned is on the frontpage README file of our [grommet github](https://github.com/grommet/grommet), check out the `Explore` section, and I also recommend joining our Slack channel for engaging with the community to get more inputs.
Please feel free to share any more inputs that can you help you get started better.
