### ISSUE TITLE
On grommet.io the "start coding" section, there playground code has a bunch of white space after the code sample

### ISSUE THREAD

**Issue by L0ZZI** [grommet/grommet-docs#320]
<img width="1034" alt="Screen Shot 2019-08-09 at 11 44 38 AM" src="https://user-images.githubusercontent.com/1753301/62801967-b754dc80-ba9b-11e9-885a-448af4f46b1b.png">

### Expected Behavior

There shouldn't be a scroll area or all that white space.

### Actual Behavior

Since there is so much space, if the cursor is in the center of the page it interrupts the scroll.

### Steps to Reproduce
 1. go to the playground on grommet.io
 2. scroll the code snippet
 3. 

### Your Environment
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
closing and moving to the grommet-site repo.
