### ISSUE TITLE
Sample codesandbox has errors

### ISSUE THREAD

**Issue by juanlanus** [grommet/grommet-docs#321]
The very useful codesandbox is polluted by a couple errors. 
https://codesandbox.io/s/github/grommet/grommet-sandbox/tree/master/

### Expected Behavior
No errors, no glitches

### Actual Behavior
1. The page opens with a "`SyntaxError  Unexpected token <`" message, before doing anything. 

2. The console is polluted with an ever repeating deprecation warning:

```
This component will be deprecated in the upcoming releases. Please refer to https://github.com/grommet/grommet/issues/2855 for more information. 
    in RoutedAnchor (created by Anonymous)
    in Anonymous (created by Route)
    in Route (created by Sandbox)
    in Sandbox 
```

### Steps to Reproduce
 1. Open https://codesandbox.io/s/github/grommet/grommet-sandbox/tree/master/
 2. See the messages (need to show the console to see #2) 

### Your Environment
* Browser Name and version: \\\\\\\\\chrome Version 76.0.3809.100 (Official Build) (64-bit)
* Operating System and version (desktop): Ubuntu 19

**Comment by ShimiSun** [comment]
@juanlanus the grommet-docs repo is a repo for grommet v1 content, and probably not the best place to file an issue too. 
Regarding the Syntax error - I've filed an issue to codesandbox a while back https://github.com/codesandbox/codesandbox-client/issues/1513

Regarding the RoutedButton issue, we'll need to refactor grommet-sandbox to implement its own RoutedButton rather than using grommet's.

**Comment by juanlanus** [comment]
Yes. I was aware of the repo thing, not that it was v1.  
I chose to file the issue here because 
  1) There is an ongoing effort to hone the docs, and 
  2) In a hardcore dev repo issues like this can get unnoticed.  

The scenario I envisioned is a guy (like me a while ago) who approaches Grommet and finds glitches all along the path. The project might be suspected of sloppiness.  
As when you meet a person, the first minutes with a new software project contribute a high proportion of the internal image you build. 

> Regarding the RoutedButton issue, we'll need to refactor grommet-sandbox to implement its own RoutedButton rather than using grommet's.
Is this button issue already filed? If so then lets close this one.

**Comment by ShimiSun** [comment]
issues on grommet-docs are easy to be missed due to low activeness of the repo. we'll be tracking the issue on the issue I linked to.

**Comment by juanlanus** [comment]
Sorry, I didn't notice this message because it's in the grommet-docs repo
 :-)

**Comment by ShimiSun** [comment]
Closing and tracking on codesandbox/codesandbox-client#1513
