### ISSUE TITLE
Split option "onResponsive" not in docs

### ISSUE THREAD

**Issue by linde12** [grommet/grommet-docs#35]
Hello hello!

I noticed, while snooping around, that the `onResponsive` option was not mentioned in the docs for `Split` but i could see it in use [here](https://github.com/grommet/grommet-docs/blob/master/src/DocsSplit.js#L151-L154)

Is it something that isn't public or should it be added to the options?

**Comment by alansouzati** [comment]
It should definitely be in the docs. PRs gladly welcome :smile:

**Comment by linde12** [comment]
Ah, will do asap! :smile:

**Comment by linde12** [comment]
Do you think this description will suffice?  English isn't my primary language i'm afraid! I tried to make some use of the description that the `priority` option uses. What do you think? Here is the description in plain text:

onResponsive   function (columns) {...}
Function that will be called when the display area changes. When space is limited the 'columns' parameter will be set to 'single'. Otherwise 'columns' will be set to 'multiple'.

priority   left|right
Which side to prioritize when space is limited. The default value is 'right'.

**Comment by linde12** [comment]
Here i made a pull request for now. Let me know if i should change anything! :) #36
