### ISSUE TITLE
On IE11 or firefox, docs does not go responsive as expected with small window size

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet-docs#4]
When window is small in IE11 or firefox you do not get the nice logo and contents title as you do in chrome. Instead you have the full LHS on top, then the content/article below it.

Image at the juncture of LHS and bottom
![image](https://cloud.githubusercontent.com/assets/13527666/11078007/626b6f02-87c0-11e5-8931-96802758b139.png)

**Comment by bryanjacquot** [comment]
This is working as expected in IE11 and the latest version of grommet.
