### ISSUE TITLE
Broken link on "Hello World" page

### ISSUE THREAD

**Issue by gitname** [grommet/grommet-docs#50]
The "Get Started" link near the bottom of the [Hello World](http://www.grommet.io/docs/develop/hello-world) page, is broken (i.e. when I click it, my browser doesn't take me to the [Get Started](http://www.grommet.io/docs/develop/get-started) page).

Here's a screenshot showing the link:
![image](https://cloud.githubusercontent.com/assets/7143133/15029383/2492a2c8-1202-11e6-9a4e-15e74e7aedff.png)

According to Chrome's developer tools (shown below), the HTML element associated with the link lacks an `href` attribute:
![image](https://cloud.githubusercontent.com/assets/7143133/15029548/e1170542-1202-11e6-8f92-3d35e8d1ec2b.png)

Here's a link to the line of source code associated with the link: 
https://github.com/grommet/grommet-docs/blob/master/src/develop/HelloWorld.js#L40

**Comment by alansouzati** [comment]
Thanks for reporting this. Fixed in https://github.com/grommet/grommet-docs/commit/06abf38a188ea3bfbb87396b793cd33386e001bf
