### ISSUE TITLE
Anchor :visited styles (HPE Theme)

### ISSUE THREAD

**Issue by epilande** [grommet/grommet-docs#77]
On the [Anchor Docs](http://grommet.github.io/hpe/docs/anchor/) page, the Anchor icon & text color should be matching (in this case, they should be green).

Currently, all anchors have `:visited` styles applied (green icon, dark text).

This is inconsistent with other themes.
Also this is confusing as users will think Anchor's default style is green icon with dark text.

**Comment by epilande** [comment]
An anchor with an empty href (`href=""`), will apply `:visited` styles.

**Comment by karatechops** [comment]
This appears to be an issue with the color defaults within the HPE Grommet theme. All themes but HPE set the `$link-color` variable to a color value while the [HPE theme](https://github.com/grommet/grommet/blob/master/src/scss/hpe/_hpe.defaults.scss#L17) sets the `$link-color` value to `inherit`. This setting will inherit the HTML base color value of `#333`. 

Updating the `$brand-link-color` value in the HPE theme to `$brand-color` will resolve this issue however this will change the default Anchor styling of all HPE themed grommet applications.

**Comment by bryanjacquot** [comment]
@karatechops the intended behavior is to change the font color in the HPE theme to $brand-color.  The only concern is if this would change the standard anchors (non-primary) as those are only 16px font.  The HPE green does not meet WCAG 2.0 AA rating on a white background unless the font is at least 19px.  I wonder if that's the reason this was done differently in the first place.

**Comment by karatechops** [comment]
@bryanjacquot changing the link color to `$brand-color` would adjust all the links. A potential workaround is to use SCSS to target the primary Anchors and set their color to `$brand-color`, the primary Anchors default to 19px while base Anchor styling is 16px. With this solution the non primary Anchor tags would remain `#333`. I can submit a PR if this sounds like a fix.

**Comment by bryanjacquot** [comment]
@karatechops yep, that sounds like the right direction.  Thanks!

**Comment by karatechops** [comment]
Proposed fix in grommet PR [#879](https://github.com/grommet/grommet/pull/879)
