### ISSUE TITLE
Button is unnecessarily wide in docs

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet-docs#79]
Some of the docs page have buttons which are unnecessarily wide
### Expected Behavior

Button should have regular width
### Actual Behavior

Button has extra width
### URL or screen shot exhibiting the issue

![screen shot 2016-08-12 at 10 46 41 am](https://cloud.githubusercontent.com/assets/1207250/17631765/44e88cf6-607a-11e6-9656-379a268c6377.png)
### Your Environment
- Browser Name and version: Any
- Operating System and version (desktop or mobile): Any

**Comment by bryanjacquot** [comment]
CodePen illustrating the issue.  The default for `align-items` for flexbox is `stretch` which is causing the issue.   http://codepen.io/grommet/pen/ZOgYYw?editors=0010

**Comment by jwijay** [comment]
grommet-docs PR pending: https://github.com/grommet/grommet-docs/pull/111

**Comment by jwijay** [comment]
Issue resolved by PR #111
