### ISSUE TITLE
Investigate analytics for the github site

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet-docs#80]
It seems that analytics is not running for the new site

**Comment by alansouzati** [comment]
Also investigate why google cache is not rendering properly.

http://webcache.googleusercontent.com/search?q=cache:kCYoSj2FUYsJ:www.grommet.io/&num=1&hl=en&gl=us&strip=0&vwsrc=0

This url blinks in chrome. it works well in safari

**Comment by bryanjacquot** [comment]
Moved google cache part of the issue to #90

**Comment by bryanjacquot** [comment]
Analytics are working properly for the website.  Fixed for Grommet blog in https://github.com/grommet/grommet-blog/commit/1c95cd7328177d8546e47eb5ba283330b0d7560b
