### ISSUE TITLE
Update component documentation to latest structure

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet-docs#87]
Examples no longer have import statements and it can be tricky for new users to correctly import components.

**Comment by bryanjacquot** [comment]
Put simple example in first section.
Add Usage section with import.
Rename 'Options' -> 'Properties'.
Move examples to separate screens, unless there is only one and it is simple.

**Comment by ericsoderberghp** [comment]
Fixed the over the last several days in multiple commits.
