### ISSUE TITLE
Import statements for some icons doesn't work

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet-docs#97]
It appears icons that have a hypen in their name get messed up when being displayed in the docs.  For example, `link-next` appears like this (notice the spaces):

```
var Link next = require('grommet/components/icons/base/Link next');
//or var Link next = Grommet.Icons.Base.Link next
<Link next />
```

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet-docs/commit/aa28e2760a34797a754118943326b1fda342af40
